# Generated by Django 4.0.2 on 2022-02-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turmas', '0003_restricao_de_matricula_unica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ('turma', 'data')},
        ),
    ]
